/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  IsBoolean,
  ValidateNested,
} from "class-validator";

import { ReservationUpdateManyWithoutRoomsInput } from "./ReservationUpdateManyWithoutRoomsInput";
import { Type } from "class-transformer";
import { RoomServiceUpdateManyWithoutRoomsInput } from "./RoomServiceUpdateManyWithoutRoomsInput";

@InputType()
class RoomUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  roomNumber?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pricePerNight?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  availability?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => ReservationUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => ReservationUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => ReservationUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  reservations?: ReservationUpdateManyWithoutRoomsInput;

  @ApiProperty({
    required: false,
    type: () => RoomServiceUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => RoomServiceUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => RoomServiceUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  roomServices?: RoomServiceUpdateManyWithoutRoomsInput;
}

export { RoomUpdateInput as RoomUpdateInput };
